### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by CodeCash** [Jense5/Vire#1]
$ vire https://open.spotify.com/user/jochenbernard/playlist/24lu9j2xm62TOdFf5lUKif
Downloading progress: [########                                          ] 16%
Error caught on signal handler: <bound method ?.result of <Scraper(Scraper-1, started)>>
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/internet/defer.py", line 577, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Library/Python/2.7/site-packages/scrapy/core/engine.py", line 275, in <lambda>
    spider=spider, reason=reason, spider_stats=self.crawler.stats.get_stats()))
  File "/Library/Python/2.7/site-packages/scrapy/signalmanager.py", line 23, in send_catch_log_deferred
    return signal.send_catch_log_deferred(*a, **kw)
  File "/Library/Python/2.7/site-packages/scrapy/utils/signal.py", line 53, in send_catch_log_deferred
    *arguments, **named)
--- <exception caught here> ---
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/internet/defer.py", line 139, in maybeDeferred
    result = f(*args, **kw)
  File "/Library/Python/2.7/site-packages/scrapy/xlib/pydispatch/robustapply.py", line 54, in robustApply
    return receiver(*arguments, **named)
  File "/usr/local/bin/Cellar/Vire/src/scraper.py", line 45, in result
    self.youtube.download(playlist, self.path)
  File "/usr/local/bin/Cellar/Vire/src/youtube.py", line 35, in download
    Youtube.tag(track, path)
  File "/usr/local/bin/Cellar/Vire/src/youtube.py", line 46, in tag
    audio['\xa9alb'] = str(track['album_name'])
$ odec can't encode character u'\xdc' in position 32: ordinal not in range(128)

**Comment by Jense5** [comment]
Fixed in Beta 0.1.1.
